### ISSUE TITLE
MarkdownView 使用时报错

### ISSUE THREAD

**Issue by ljhao24** [LiYanan2004/MarkdownView#10]
因为我之前使用过另一个叫做MarkdownText的框架，在那个框架中，我可以这样显示markdown内容：
``` swift
import SwiftUI
import MarkdownText

struct SampleUI: View {
  var body: some View {
    ScrollView {
        MarkdownText("**Hello** there!")
    }
  }
```
所以我以为用您的这个框架也可以一样使用，我按照因此我写了下面这样的代码：
``` swift
import SwiftUI
import MarkdownView

struct ContentView: View {
    var body: some View {
        MarkdownView("This is the Apple's **newly published** [swift-markdown](https://github.com/apple/swift-markdown)")

    }
}
```
但是并不能运行，共有3条报错

1. Cannot convert value of type 'String' to expected argument type 'NSCoder'
2. Missing argument label 'coder:' in call
3. Struct 'ViewBuilder' requires that 'MarkdownView' conform to 'View'
我使用的是Xcode14.3版本。

**Comment by LiYanan2004** [comment]
@ljhao24 你可以仔细看下我的 View 构造方法，`MarkdownView(text: "text")`，注意这里有一个 `text:`

**Comment by ljhao24** [comment]
你好，这个我之前也尝试过，仍然是报错，提示MarkdownView不接受任何argument，所以我才把text:去掉尝试了，但是都会报错。
<img width="392" alt="image" src="https://github.com/LiYanan2004/MarkdownView/assets/76099355/94d2010d-8969-4c03-9c1d-c2d75aa4170a">

**Comment by LiYanan2004** [comment]
你可以尝试新建一个 Xcode 项目来单独尝试 MarkdownView，或者如果你方便的话可以提供下 `ContentView` 的完整代码嘛

**Comment by ljhao24** [comment]
因为之前一直不成功，所以我就是在一个新建的项目中进行测试的，只有默认的文件和MarkdownView的package
<img width="258" alt="image" src="https://github.com/LiYanan2004/MarkdownView/assets/76099355/974f3533-5ab5-4b5c-893b-88a1be0adfb4">
我的`ContentView.swift`文件代码只有下面这两段
``` swift
import SwiftUI
import MarkdownView

struct ContentView: View {
    var body: some View {
        MarkdownView(text: "This is the Apple's **newly published** [swift-markdown](https://github.com/apple/swift-markdown)")

    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```
`MarkdownTestApp`文件代码如下
``` swift
import SwiftUI

@main
struct MarkdownTestApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**Comment by LiYanan2004** [comment]
你貌似是搞错了，我的MarkdownView到现在最新的版本也只有 1.3.0，你怎么就 1.9.1 了？

你应该是安装了别人的，跟我的重名了🤣

你安装 SPM 的时候，用这个 URL，https://github.com/liyanan2004/markdownview

**Comment by ljhao24** [comment]
确实是我搞混了，我先用了那个版本的，一直报错，才又找到了你的方案，但是建立的项目太多，地址搞混了🤣。打扰了 谢谢你的帮助
