### ISSUE TITLE
Could not find module 'MarkdownView' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by fahidattique55** [LiYanan2004/MarkdownView#11]
I am facing this issue. I have excluded arch arm64 in my build setting. Any idea how I can get rid of this issue?

<img width="787" alt="image" src="https://github.com/LiYanan2004/MarkdownView/assets/12518061/8d0eaf85-1ce8-40a1-803f-e1bcd07c92ed">

**Comment by LiYanan2004** [comment]
Have you ever tried to clean the build folder via Command Shift K, and then build it again?

**Comment by fahidattique55** [comment]
Yes, It didn't work. Try using any cocoapods with this package in your project and exclude arm64. you should see this error.

**Comment by LiYanan2004** [comment]
Which version of Xcode are you using now?

**Comment by LiYanan2004** [comment]
@fahidattique55 I can't reproduce this on my side. I'm not quite familiar with CocoaPods.

But still found some solutions: https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator/76525001#76525001.

This forum may help you. If that helps you solve the issue, don't forget to share the solution with me. Thanks

**Comment by LiYanan2004** [comment]
Closed due to the unresponsiveness. If you still experience the issue, please reopen this issue and offer more context.
