### ISSUE TITLE
It is not possible to achieve a printer effect in a Stream mode similar to ChatGPT

### ISSUE THREAD

**Issue by WalterZou** [LiYanan2004/MarkdownView#15]
```
MarkdownView(text: markdownText)
```
When using the Stream mode of the OpenAI API, the `markdownText` in the above code will change in real-time based on the content returned by the API. However, the updates on the UI cannot keep up with the addition of content and will have a delay of 1-3 seconds for updating large blocks of text, thus unable to achieve the typewriter effect.

**Comment by LiYanan2004** [comment]
This delay is called debounce. It can hugely improve performance when live previewing a large markdown file. Currently, it will have a 0.3s debounce. 

Maybe introducing a modifier to disable debounce works for your use case. But the performance when displaying a huge markdown may decrease significantly.(But for ChatGPT‘s sample code, maybe enough)

**Comment by WalterZou** [comment]
Yes, after adjusting the debounce to 0.01 seconds, I achieved the printer effect. However, I have not yet assessed the increase in performance consumption caused by this.

**Comment by LiYanan2004** [comment]
Hello. I added a new `MarkdownRenderingMode` for you to choose. 

Try this: 

1. Update your package to `rendering-mode` branch.
2. No STEP 2. :)
> Now, default rendering mode is `immediate`.

**Comment by WalterZou** [comment]
A big thank you

**Comment by LiYanan2004** [comment]
Try it out and give me some feedbacks. Thanks😉

**Comment by WalterZou** [comment]
Already updated and currently no significant performance issues have been found, thanks a lot

**Comment by LiYanan2004** [comment]
Hope you enjoy this package😊

**Comment by LiYanan2004** [comment]
1.4.0 released. I will delete that fix branch.
