### ISSUE TITLE
Can get md  block height 

### ISSUE THREAD

**Issue by CooperHash** [LiYanan2004/MarkdownView#17]
**The feature you want to get in MarkdownView** 
get md block height like MarkdownView(text: "xxx")..onRendered { height in 
          print(height)
        }

**Additional context**
in some case, we need to know the height of MarkdownView, so i wonder if we can add a new api

**Comment by LiYanan2004** [comment]
Actually, you can use SwiftUI's native way to get view height.

```swift
MarkdownView(text: document.text, baseURL: URL(filePath: baseURL))
    .overlay {
        GeometryReader { proxy in
            Color.clear
                .task(id: proxy.size.height) {
                    print("height: \(proxy.size.height)")
                }
        }
    }
```

This value can be dynamic when size changes.

https://github.com/LiYanan2004/MarkdownView/assets/37542129/bfcde9ec-4d98-4288-9be7-54771cc3c0f2
