### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by hugo53** [LiYanan2004/MarkdownView#19]
**The feature you want to get in MarkdownView** 
Dear @LiYanan2004 , 

Thank you once again for this great package. Do you have any plan to support Latex syntax?

**Comment by LiYanan2004** [comment]
Maybe yes. But it might take a looooong time.

**Comment by hugo53** [comment]
Thank you for confirmation @LiYanan2004 !

**Comment by LiYanan2004** [comment]
@hugo53 I have updated the block directive which unlocks the possibility to add LateX support for Markdown content. Hope it will be useful. 

If you’re interested in it, you can test it out by switching to [block-directive-improvements](https://github.com/LiYanan2004/MarkdownView/tree/block-directive-improvements) branch and check out my description in the PR mentioned above.

**Comment by hugo53** [comment]
@hugo53 Thank you, let me check that PR.

**Comment by LiYanan2004** [comment]
There is no definition of Latex in CommonMark. Hope that PR will help you. If there is any technical problems you can reopen the issue or create a new issue. Thanks

**Comment by hugo53** [comment]
Thank you for great work. I will check more with the latest release for sure.
