### ISSUE TITLE
这个库真的写的不错，提个代码复制的需求

### ISSUE THREAD

**Issue by JohannLai** [LiYanan2004/MarkdownView#2]
请问下这里可以增加一个复制代码的按钮吗？ 
![image](https://user-images.githubusercontent.com/10769405/230557334-2b060885-5ff6-4526-89ff-40b2675c3e57.png)

类似于这样：

![image](https://user-images.githubusercontent.com/10769405/230557517-a358748f-c65c-4cfb-9306-0fb0b26adeeb.png)

**Comment by LiYanan2004** [comment]
好，明白了。下个版本会加上，下周末之前应该会上，快的话这两天发。

**Comment by JohannLai** [comment]
可以参考一下 `react-markdown` 这个库的 UI ~

**Comment by LiYanan2004** [comment]
问个问题，你觉得是用 modifier 的方式让开发者可以自定义 button 的样式好呢，还是固定一个样式比较好？

**Comment by JohannLai** [comment]
@LiYanan2004 默认一个按钮就好～ 后续可以增加自定义的按钮配置。 这样可以增加易用性

**Comment by LiYanan2004** [comment]
新的问题就重新开一个 issue 吧

**Comment by LiYanan2004** [comment]
另外，我已经把包含 Copy Button 的代码 push 到 dev 分支了，你可以去看下

**Comment by JohannLai** [comment]
在 macos 上验证没问题，在 iOS 上可以默认展示这个按钮吗？ 而不是 hover 展示 😆

**Comment by LiYanan2004** [comment]
只是一个雏形 先预览一下 我今天回来之后再继续完善哈🤣

**Comment by LiYanan2004** [comment]
@JohannLai Pushed

**Comment by JohannLai** [comment]
awesome!

**Comment by gongzhang** [comment]
这个仓库实现的太棒了，优雅，令人感到舒适。
