### ISSUE TITLE
Foreground Style per text type

### ISSUE THREAD

**Issue by Lancelotbronner** [LiYanan2004/MarkdownView#20]
**The feature you want to get in MarkdownView** 

I'd like to render Dungeons & Dragons books using markdown. Some headers should use a different foreground style than others.

**Describe that feature in detail**

Just like you have `font(_: Font, for: MarkdownFontProvider.TextType)`, I'd like a way to configure foreground styles such as `foregroundStyle(_: some ShapeStyle, for: MarkdownFontProvider.TextType)`.

**Additional context**

My objective:

<img width="189" alt="Screenshot 2023-07-27 at 7 51 07 PM" src="https://github.com/LiYanan2004/MarkdownView/assets/18574607/4186f5fc-7cf0-4bda-8566-132433383733">

**Comment by LiYanan2004** [comment]
Thanks for your advice. Pretty nice suggestion. In fact, I have plans to add more customizations to components in MarkdownView.

Your request will become live soon.

**Comment by LiYanan2004** [comment]
It’s available as a beta at [customize-foreground-style](https://github.com/LiYanan2004/MarkdownView/tree/customize-foreground-style) branch.

### Tips:

- You can change foreground style in real-time via `.foregroundStyle(_:for:)` modifier while MarkdownView will handle all the things for you.
- To take advantage of the built-in optimization of `.foregroundStyle(_:for:)`, you should use `@State` to switch between styles or use static members instead of using expressions like `useMaterialStyle ? AnyShapeStyle(.regularMaterial) : AnyShapeStyle(.primary)`

#### Examples

```swift
// ✅
@State private var h1Style = AnyShapeStyle(.orange)
MarkdownView(...)
    .foregroundStyle(h1Style, for: .h1)
// ✅
@State private var useBlue = false
MarkdownView(...)
    .foregroundStyle(useBlue ? .blue : .primary, for: .h1)
// ❌
@State private var useMaterial = false
MarkdownView(...)
    .foregroundStyle(useMaterialStyle ? AnyShapeStyle(.regularMaterial) : AnyShapeStyle(.primary), for: .h1)
```

**Comment by Lancelotbronner** [comment]
I'll test that as soon as possible! I'm currently experiencing an issue with Xcode & macOS beta which is preventing me from launching projects.

**Comment by Lancelotbronner** [comment]
Works great, does exactly what I need! Thank you very much!

**Comment by LiYanan2004** [comment]
Update modifier to `foregroundStyleGroup(_:)`. The original `MarkdownForegoundStyleProvider` has been removed.

You can use foregroundStyle(_:for:) to modify a single component.

But if there are many components to be adjusted, you should construct a foreground style group like this:

```swift
struct HierarchicalHeader: MarkdownForegroundStyleGroup {
    var h1 = HierarchicalShapeStyle.primary
    var h2 = HierarchicalShapeStyle.secondary
    var h3 = HierarchicalShapeStyle.tertiary
    var h4 = HierarchicalShapeStyle.quaternary
}

extension MarkdownForegroundStyleGroup where Self == HierarchicalHeader {
    static var hierarchical: HierarchicalHeader { .init() }
}
```

Attach style group:

```swift
MarkdownView(...)
    .foregroundStyleGroup(.hierarchical)
```

This feature will be merged to main very soon. Hope you enjoy this package.
