### ISSUE TITLE
Add accessibly annotations or a way to decorate headers and lists with them

### ISSUE THREAD

**Issue by opi-smccoole** [LiYanan2004/MarkdownView#28]
**The feature you want to get in MarkdownView** 
Add accessibly annotations or a way to decorate headers and lists with them

**Describe that feature in detail**
Currently items like headers and lists are just composed of native Text views and these render well and it looks great.  But when read by VoiceOver, they are just read and not announced as "<text>, heading" and lists do not have the "<first item>, in list" and "out of list" when the next element past the list is read, etc.  Could additions be made to the library to either add these accessibility traits by default or a way to add them via something like the custom providers that exist for Image and Blocks now?

**Behavior in different OS**
* iOS / iPadOS: all text is read without any a11y annotations
* macOS: all text is read without any a11y annotations
* watchOS: not tested
* tvOS: not tested

**Additional context**
You can see the current reading behavior by bringing up anything in MarkdownView and then using the AccessibilityInspector or Voiceover to read it.

**Comment by LiYanan2004** [comment]
Great suggestions, thank you, I just finished my final exam and I'll investigate this later. 

It would be great if you can help me. Maybe we can draft a PR for this? 😁

**Comment by LiYanan2004** [comment]
Hi @opi-smccoole 

The PR for this issue is merged. You can upgrade package to 1.7.0 to check it out.

if there’s another related issue, feel free to raise a new issue
