### ISSUE TITLE
在纯字符串下无法正常渲染

### ISSUE THREAD

**Issue by LiYanan2004** [LiYanan2004/MarkdownView#3]
我发现用最新的 main 分支的代码，纯字符串或者是下面的这个这个用例渲染不出来内容， 空白

```swift
MarkdownView(text: "This is the Apple's **newly published** [swift-markdown](https://github.com/apple/swift-markdown)")
```

但是呢，前面加个 # 就开始有内容 

```swift
MarkdownView(text: "# This is the Apple's **newly published** [swift-markdown](https://github.com/apple/swift-markdown)")
```

<img width="534" alt="image" src="https://user-images.githubusercontent.com/10769405/230635358-44cb0656-e1cd-4359-b585-84334c91a97e.png">

内容里面插入一段代码也没问题。

_Originally posted by @JohannLai in https://github.com/LiYanan2004/MarkdownView/issues/2#issuecomment-1500392320_

**Comment by LiYanan2004** [comment]
补丁已经 push 到 dev 分支了

**Comment by JohannLai** [comment]
验证没问题 点赞👍
