### ISSUE TITLE
请问下如何实现选中复制功能

### ISSUE THREAD

**Issue by ynpl** [LiYanan2004/MarkdownView#30]
请问下设置什么属性才能实现选中复制

**Comment by ynpl** [comment]
我加了.textSelection(.enabled) 之后发现只能单行复制

**Comment by LiYanan2004** [comment]
> 我加了.textSelection(.enabled) 之后发现只能单行复制

目前确实是这样子的 只有普通文本可以跨段落选中 目前还是没有什么可用的改进方案🙁

**Comment by ynpl** [comment]
好吧 感谢回复
